FROM php:7.4-apache

RUN a2enmod rewrite

RUN docker-php-ext-install mysqli

RUN pecl install xdebug
RUN docker-php-ext-enable xdebug

RUN apt update; apt install -y mariadb-client vim

RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
